export const baseURL='http://api.suhyeon.shop'
//export const baseURL='http://localhost:3065'
export const gikalURL='http://api.suhyeon.shop/gik'
export const cafeURL='http://ahah12k.cafe24.com/jin'
export const youTubeLink='https://www.youtube.com/watch?v='
export const youTubeFrame='https://www.youtube.com/embed/'
